### PR TITLE
feat(notification): add ActionInvoked signal

### LINKED ISSUE #31: Support ActionInvoked signal in Notification portal
https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Notification

### PR DESCRIPTION
**Pull request by Merrit**
Adds support for the `ActionInvoked` notifications signal.

Resolves #31

### CODE REVIEW

**Comment by Merrit** [comment]
Using `example/notification.dart` seems to be working fine, but I am having trouble creating a test - at the moment the test I have just times out after 30 seconds without the stream emitting anything.

**Comment by Levi-Lesches** [comment]
@robert-ancell is this repo still active?

**Comment by robert-ancell** [comment]
It is, but this PR is still a draft.

**Comment by Levi-Lesches** [comment]
Sorry @robert-ancell not to speak on other people's behalf, I came from https://github.com/MaikuB/flutter_local_notifications/pull/1987 where this is a blocker. 

Seems @Merrit has un-drafted this so we should be good now

**Comment by Merrit** [comment]
Doesn't seem like the repo contents have really changed, and this was fully functional when created. :+1:

**Review by robert-ancell — APPROVED** [review]
Thanks!

**Pull request merged**
