### PR TITLE
refactoring: (split classes to different files)

### PR DESCRIPTION
**Pull request by aospiridonov**
Classes are split into different files

### CODE REVIEW

**Comment by robert-ancell** [comment]
Thanks for this, I've also got a branch in which I've been working on this. If you want to continue with this PR, can you make a PR that just has one portal split out? That way it's easier to review and then land the other portal changes.

**Comment by aospiridonov** [comment]
> 
I specifically separated the current state portals to different files in this PR to make it easier to maintain the code further.

**Comment by aospiridonov** [comment]
> Thanks for this, I've also got a branch in which I've been working on this. If you want to continue with this PR, can you make a PR that just has one portal split out? That way it's easier to review and then land the other portal changes.

I suggest syncing and adding new portals in parallel. If everything is in one dart file, there will be difficulties with the merge.

**Comment by robert-ancell** [comment]
See https://github.com/canonical/xdg_desktop_portal.dart/pull/50 for the first step in refactoring the internal classes so things can be split out.

**Pull request closed without merging**
